return require('packer').startup(function(use)
  -- Packer can manage itself
  use 'wbthomason/packer.nvim'
  use 'akinsho/bufferline.nvim'
  use 'nvim-tree/nvim-web-devicons' 
  use 'numToStr/Comment.nvim'
  use 'L3MON4D3/LuaSnip'
  use 'hrsh7th/cmp-buffer'
  use 'hrsh7th/cmp-cmdline'
  use 'hrsh7th/cmp-nvim-lsp'
  use 'hrsh7th/cmp-path'
  use 'saadparwaiz1/cmp_luasnip'
  use 'github/copilot.vim'
  use 'ibhagwan/fzf-lua'
  use 'lewis6991/gitsigns.nvim'
  use 'gruvbox-community/gruvbox'
  use 'lukas-reineke/indent-blankline.nvim'
  use 'nvim-lualine/lualine.nvim'
  use 'alvarosevilla95/luatab.nvim'
  use 'windwp/nvim-autopairs'
  use 'hrsh7th/nvim-cmp'
  use 'nvim-treesitter/nvim-treesitter'
  use 'kyazdani42/nvim-web-devicons'
  use 'nvim-lua/plenary.nvim'
  use 'luochen1990/rainbow'
  use 'ap/vim-css-color'
  use 'szw/vim-maximizer'
  use { 'prettier/vim-prettier', run = 'yarn install' }

end)
